---
driver:
  name: docker
  # Mac client tries, by default, is setting use_sudo to true
  # https://github.com/test-kitchen/kitchen-docker/issues/201
  use_sudo: false

provisioner:
  name: chef_zero
  require_chef_omnibus: 13
  deprecations_as_errors: true

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[apt::default]
      - recipe[bcs_nginx::default]
    attributes:
      nginx:
        kibana_available: true
        monit_available: true
  # No sites created
  - name: empty
    run_list:
      - recipe[apt::default]
      - recipe[bcs_nginx::default]
    attributes:
      nginx:
        kibana_available: false
        monit_available: false
