---
driver:
  name: docker

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[bcs_nginx::default]
    attributes:
  - name: monit_virtual_server
    run_list:
      - recipe[monit::default]
      - recipe[bcs_nginx::default]
      - recipe[bcs_nginx::monit_virtual_server]
    attributes:

