---
driver:
  name: vagrant
  # network:
    # Running multiple VMs cause
    #  problems with networks - use these if debugging one instance
    # - ["forwarded_port", {guest: 80, host: 8080}]
    # - ["private_network", {ip: "192.168.33.33"}]

provisioner:
  name: chef_zero
  product_name: chef
  product_version: latest
  deprecations_as_errors: true

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: ubuntu-18.04

suites:
  - name: default
    run_list:
      - recipe[apt::default]
      - recipe[bcs_nginx::default]
    attributes:
      nginx:
        kibana_available: true
        monit_available: true
  # No sites created
  - name: empty
    run_list:
      - recipe[apt::default]
      - recipe[bcs_nginx::default]
    attributes:
      nginx:
        kibana_available: false
        monit_available: false
