---
driver:
  name: docker
  # Mac client tries, by default, is setting use_sudo to true
  # https://github.com/test-kitchen/kitchen-docker/issues/201
  use_sudo: false

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt::default]

suites:
  - name: default
    run_list:
      - recipe[bcs_nginx::default]
    attributes:
      nginx:
        kibana_available: true
        monit_available: true
  # No sites created
  - name: empty
    run_list:
      - recipe[bcs_nginx::default]
    attributes:
      nginx:
        kibana_available: false
        monit_available: false

