---
driver:
  name: docker

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[bcs_nginx::default]
    attributes:
      nginx:
        monit_available: true
        kibana_available: true
  # No sites created
  - name: empty
    run_list:
      - recipe[bcs_nginx::default]
    attributes:
      nginx:
        monit_available: false
        kibana_available: false

